version: '3.8'

services:
  app:
    build: .
    container_name: emotion-helper
    restart: unless-stopped
    ports:
      - "7860:7860"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    volumes:
      - ./.env:/app/.env  # 挂载环境变量文件
      - ./data:/app/data  # 挂载数据目录，实现数据持久化
    networks:
      - emotion-helper-network

networks:
  emotion-helper-network:
    driver: bridge
